# Generated by Django 5.2 on 2025-04-21 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='like',
            new_name='likes',
        ),
    ]
